### ISSUE TITLE
How to use hard negatives for training VLM2Vec?

### ISSUE THREAD

**Issue by haon-chen** [TIGER-AI-Lab/VLM2Vec#12]
Hi, congrats to such fine work done! 
I see some of subsets have neg_text and neg_image_path, but neither of them are used in Training_Dataset or MMEBModel. Could you add the usage of possible multiple hard negatives into your code?

**Comment by XMHZZ2018** [comment]
Thank you for your interest in our work!

Initially, we employed various methods to collect hard negatives, tailored to different datasets. However, since this process was time-consuming and required multiple iterations, we decided not to include hard negatives in the first version of the VLM2Vec release. Instead, we adopted GradCache, which allowed us to use a relatively large batch size of 2K to mitigate the missing of hard negatives.

However, hard negatives are definitely important and will enhance our model's performance. In the future, we plan to incorporate hard negatives into our training data and release an updated version of the model.

**Comment by XMHZZ2018** [comment]
@lijiaoyang 
We plan to release this feature along with a checkpoint trained with hard negatives in about two weeks. Currently, we are updating this part in the ```b3``` branch of this repo— it's mostly finished, but a few components still need to be updated.

**Comment by lijiaoyang** [comment]
> [@lijiaoyang](https://github.com/lijiaoyang) We plan to release this feature along with a checkpoint trained with hard negatives in about two weeks. Currently, we are updating this part in the `b3` branch of this repo— it's mostly finished, but a few components still need to be updated.

Thank you for replying to me so quickly!
