### ISSUE TITLE
Could this model provide embeddings for videos? 

### ISSUE THREAD

**Issue by lly0571** [TIGER-AI-Lab/VLM2Vec#5]
Phi3.5-Vision theoretically has the capability to handle video clip inputs. Have you attempted to use this embedding model on video  inputs?
I attempted to process videos using the following code, randomly sampling 5 key frames from each video.
```python
def process_video_input(processor,model,video_path,video_frames_path,prompt="Represent the given video."):
    """Process video input
    """
    save_keyframes(video_path,video_frames_path)
    images = [] 
    placeholder = "" 
    frames = len(os.listdir(video_frames_path))
    for i in range(1,min(6,frames)): # 5-> 22G 6->27G 7-> OOM
        with open(f"{video_frames_path}/keyframe_{i}.jpg", "rb") as f:
            images.append(Image.open(f"{video_frames_path}/keyframe_{i}.jpg"))
            placeholder += f"<|image_{i}|>\n"
    prompt = placeholder +prompt
    inputs = processor(prompt, images, return_tensors="pt")
    inputs = {key: value.to('cuda') for key, value in inputs.items()}
    qry_output = model(qry=inputs)["qry_reps"]
    return qry_output
```
Here is a visualized tsne result for it:
![Video](https://github.com/user-attachments/assets/4f970fa0-908b-4d36-9837-bc695b243302)

**Comment by xinyanghuang7** [comment]
Hey, thanks for trying it out, it gave me some inspiration.

Could you please provide me the script you used to process the video and get the output, it would help me a lot!

Thanks!

**Comment by XMHZZ2018** [comment]
@xinyanghuang7 I think you might want to try Qwen2-VL, which has better support for video processing. Our team has released the image-level VLM2Vec model based on Qwen2-VL, and I believe you can use it directly for extracting video embeddings. (Adapting code from: https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct. Though the results might not be very strong, since we haven't fine-tuned it specifically for video tasks.) We're planning to release the video-based VLM2Vec in the coming weeks. Thanks for your patience!
