### ISSUE TITLE
How to train the model with my own data?

### ISSUE THREAD

**Issue by B-201** [TIGER-AI-Lab/VLM2Vec#8]

**Comment by XMHZZ2018** [comment]
@B-201 

Could you please provide some details about your data? For example, data format, modality, or whether it includes hard negatives. Thanks!

**Comment by B-201** [comment]
> @B-201
> 
> Could you please provide some details about your data? For example, data format, modality, whether it includes hard negatives, whether you want to train from scratch or on top of our version, etc Thanks!

Thank you for your response! What I mean is, for example, if I want to prepare a Chinese dataset similar to MMEB, what formatting requirements should this dataset meet? And is there any data preprocessing code available?

**Comment by XMHZZ2018** [comment]
Thanks for letting me know!

Our training data is released on Hugging face: https://huggingface.co/datasets/TIGER-Lab/MMEB-train.

In general, there are four important fields: ``qry``: which is the text from the query side (also including text instruction); ``qry_image_path``: which is the path of the query side image; ``pos_text``: which is the text from the target side; ``pos_image_path``: which is the path of the target side image. ``neg_text`` and ``neg_image_path`` are for hard negatives. You could decide whether to use hard negatives based on how easily you can construct high-quality hard negatives for your own dataset.

I will upload my preprocessing code soon. Since the raw data for my 36 datasets are quite different from each other, there isn't actually a uniform preprocessing code, so it may not be directly applicable to your data. But the final data format is fixed, as I mentioned above. Hope this information is useful. If you need any assistance, feel free to let me know, and I'd be happy to help.

**Comment by B-201** [comment]
Got it! It is very detailed, thank you!

**Comment by XMHZZ2018** [comment]
@B-201 
Yes, you are correct. Models with different image placeholder require some simple preprocessing of the data.
